version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pickdb
      POSTGRES_USER: pickuser
      POSTGRES_PASSWORD: pickpass
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pickuser -d pickdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build: ./server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pickdb
      DB_USER: pickuser
      DB_PASSWORD: pickpass
      CORS_ORIGINS: "http://localhost:3000,http://localhost:4173"
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      VITE_PICK_API: http://localhost:8080
    depends_on:
      server:
        condition: service_healthy
    ports: ["3000:3000"]