name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server:
    name: Server build & tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["21"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build & test server
        working-directory: server
        run: mvn -B -Pstrict clean package

  client:
    name: Client build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install and build client
        working-directory: client
        run: |
          npm ci
          npm run build
